enum RequestState {
  initialState,
  zakatLoading,
  zakatProductsLoading,
  productsLoading,
  getZakatProductsByKilosLoading,
  getZakatProductsByZakatIdLoading,
  //------------------
  zakatLoaded,
  zakatProductsLoaded,
  productsLoaded,
  getZakatProductsByKilosLoaded,
  getZakatProductsByZakatIdLoaded,
  //------------------
  zakatError,
  zakatProductsError,
  productsError,
  getZakatProductsByKilosError,
  getZakatProductsByZakatIdError,
  //------------------
  insertLoading,
  updateLoading,
  deleteLoading,
  //------------------
  insertDone,
  updateDone,
  deleteDone,
  //------------------
  insertError,
  updateError,
  deleteError,
}
